import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, "..");
const outputDirectory = path.join(projectRoot, "out");
const serviceWorker = `/* Generated by scripts/generate-sw.mjs to retire offline caching. */
const CACHE_PREFIX = "nordic-trip-";

self.addEventListener("install", (event) => {
  event.waitUntil(self.skipWaiting());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const scope = self.registration.scope;
    const windowClients = await self.clients.matchAll({ type: "window" }).catch(() => []);

    const cacheNames = await self.caches.keys().catch(() => []);
    await Promise.all(
      cacheNames
        .filter((cacheName) => cacheName.startsWith(CACHE_PREFIX))
        .map((cacheName) => self.caches.delete(cacheName).catch(() => false)),
    );

    await self.registration.unregister().catch(() => false);
    await Promise.all(
      windowClients
        .filter((client) => client.url.startsWith(scope))
        .map((client) => client.navigate(client.url).catch(() => null)),
    );
  })());
});
`;

await fs.mkdir(outputDirectory, { recursive: true });
await fs.writeFile(path.join(outputDirectory, "sw.js"), serviceWorker, "utf8");
console.log("Generated out/sw.js to remove Nordic offline caches and unregister their worker.");
